# Generated by Django 4.0.2 on 2022-04-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_alter_rate_source_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars'),
        ),
    ]
